on: [push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: poetry install -vvv --no-interaction
      - run: |
          poetry run coverage run -m pytest
          poetry run coverage report
          poetry run coverage html
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: src/htmlcov
