on: [push]
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: install dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry install --no-interaction
      - name: check
        run: poetry run mypy src tests
  pyre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: install dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry install --no-interaction
      - name: install pyre
        run: poetry add -D pyre-check
      - name: check
        run: poetry run pyre --source-directory src
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: install dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry install --no-interaction
      - uses: actions/setup-node@v2
      - name: install pyright
        run: npm install -g pyright
      - name: check
        run: poetry run pyright src tests
  pytype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: install dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry install --no-interaction
      - name: install pytype
        run: poetry add -D pytype
      - name: check
        run: poetry run pytype src tests
